version: '2'
services:

  php:
    build: docker/php
    #tty: true
    ports:
      - '9002:9000'
    volumes:
      - ./:/var/www/symfony:cached
    links:
      - db
  nginx:
    build: docker/nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
  db:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=rootPass"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=rootPass"
      - "MYSQL_DATABASE=menuar"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/data/db:/var/lib/mysql"
